### ISSUE TITLE
Change rule level breaks running eslint from CLI

### ISSUE THREAD

**Issue by jorgev259** [neostandard/neostandard#189]
When changing one of the rule levels and running `npx eslint` it gives the following error: 
```
Oops! Something went wrong! :(

ESLint: 9.12.0

TypeError: Key "rules": Key "@typescript-eslint/no-unused-vars": Could not find plugin "@typescript-eslint".
    at throwRuleNotFoundError (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\eslint\lib\config\rule-validator.js:66:11) 
    at RuleValidator.validate (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\eslint\lib\config\rule-validator.js:147:17)

    at new Config (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\eslint\lib\config\config.js:240:27)
    at [finalizeConfig] (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\eslint\lib\config\flat-config-array.js:216:16)   
    at FlatConfigArray.getConfigWithStatus (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\@eslint\config-array\dist\cjs\index.cjs:1102:55)
    at FlatConfigArray.getConfig (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\@eslint\config-array\dist\cjs\index.cjs:1120:15)
    at entryFilter (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\eslint\lib\eslint\eslint-helpers.js:286:40)
    at async NodeHfs.<anonymous> (file:///C:/Users/jorge/Proyectos/neo-rule-example/node_modules/@humanfs/core/src/hfs.js:560:24)

    at async NodeHfs.walk (file:///C:/Users/jorge/Proyectos/neo-rule-example/node_modules/@humanfs/core/src/hfs.js:600:3)        
    at async globSearch (C:\Users\jorge\Proyectos\neo-rule-example\node_modules\eslint\lib\eslint\eslint-helpers.js:327:26)
   ```
   
   Example config: 
```
import configPrettier from 'eslint-config-prettier'
import neostandard, { resolveIgnoresFromGitignore } from 'neostandard'

/** @type {import('eslint'.Linter.Config[]} */
  export default [
    ...neostandard({noStyle: true, ts:true}),
    {
      ignores: [...resolveIgnoresFromGitignore(), 'dist']
    },
    {rules: {
      '@typescript-eslint/no-unused-vars': 'warn'
    }},
    configPrettier
  ]
```
   
   Linting through VSCode ESLint extension works fine

**Comment by voxpelli** [comment]
Reason is that neostandard only uses the `typescript-eslint` plugin and its rules in TypeScript files as defined here:

https://github.com/neostandard/neostandard/blob/65b89ba7ed1d545665e18fab7055b28393a59b84/lib/main.js#L124-L129

So based on your config this should work:

```js
import configPrettier from 'eslint-config-prettier'
import neostandard, { resolveIgnoresFromGitignore } from 'neostandard'

/** @type {import('eslint'.Linter.Config[]} */
export default [
  ...neostandard({
    ignores: [...resolveIgnoresFromGitignore(), 'dist'],
    noStyle: true,
    ts:true,
  }),
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'warn'
    }
  },
  configPrettier
]
```

You could also opt to use `ignores` instead of `files` if you prefer – I sometimes use one, sometimes the other. If `files` matches a file that previously wasn't referenced, then it will be included in all `files`-less rule sets, possibly causing new files to be linted. But `ignores` only tells which files to _not_ lint.
